version: "3.8"

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager"
    restart: unless-stopped
    ports:
      - "28081:81"
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    expose:
      - "80"
      - "443"
    network_mode: "host"